services:
  - type: web
    name: ai-chat-bot
    env: node
    plan: free
    buildCommand: cd front && npm install
    startCommand: cd back && node server.js
    envVars:
      - key: NODE_ENV
        value: production

